### ISSUE TITLE
Nav drawer is way too wide on Nexus 6

### ISSUE THREAD

**Issue by tjhorner** [rudsonlive/NavigationDrawer-MaterialDesign#1]
![device-2015-01-11-224616](https://cloud.githubusercontent.com/assets/2646487/5699732/ad6564f2-99e3-11e4-9473-844fa3ce03b1.png)

**Comment by yoavst** [comment]
also on G3.

**Comment by rudsonlive** [comment]
Thanks for the feedback. I took the project is turned into a library and I
believe that this problem has already been solved there. Be there the link
from the library.

https://github.com/rudsonlive/NavigationDrawer-MaterialDesign

Thank.

2015-01-15 11:36 GMT-03:00 Yoav Sternberg <notifications@github.com>:

> also on G3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/1#issuecomment-70093735>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by yoavst** [comment]
I'm talking on the app that is on Play store.

**Comment by rudsonlive** [comment]
Sorry. I have not had much time to do the update.

2015-01-15 11:57 GMT-03:00 Yoav Sternberg <notifications@github.com>:

> I'm talking on the app that is on Play store.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/1#issuecomment-70097118>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by tjhorner** [comment]
@yoavst This was fixed in 61e6083, I can upload an apk if you'd like.

**Comment by rudsonlive** [comment]
Already published an apk with the fix.

Thank you for contact

2015-01-15 21:02 GMT-03:00 TJ Horner <notifications@github.com>:

> Closed #1
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/1#event-219798654>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by tjhorner** [comment]
Sweet! @yoavst
