### ISSUE TITLE
Failed to find the lib 

### ISSUE THREAD

**Issue by taimur97** [rudsonlive/NavigationDrawer-MaterialDesign#10]
I am unable to find the library .
This is my build.gradle 

apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "com.example.app"
        minSdkVersion 9
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.parse.bolts:bolts-android:1.+'
    compile fileTree(include: 'Parse-*.jar', dir: 'libs')
    compile 'com.google.android.gms:play-services:6.+'
    compile 'br.com.liveo:navigationdrawer-material:1.0.2'
}

**Comment by rudsonlive** [comment]
Friendly version 1.0.2 has the MinSDK api 14. Notes the Change log file.
Thank U

Em qui, 22 de jan de 2015 11:51, taimur97 <notifications@github.com>
escreveu:

**Comment by amouly** [comment]
Can you post the error here? What do you mean with "unable to find the library"?.

Maybe you haven't configure the repository on your main Gradle file.

By the way, the minSDK it's API 14 right now.

**Comment by taimur97** [comment]
this is the error 
![screenshot from 2015-01-22 21 35 05](https://cloud.githubusercontent.com/assets/2510169/5859771/abbf91f6-a27e-11e4-849e-6412b052e2ae.png)

**Comment by amouly** [comment]
That's because you haven't installed the Maven repository on your project.

Can you post here your "build.gradle" file? I mean the "general" build file, not the specific of your app. This file it's located on the main folder of your project.

**Comment by taimur97** [comment]
This is my main build.gradle file 

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}

**Comment by amouly** [comment]
That's weird. I have the same configuration file and the build just works.

Try deleting the "mavenCentral()" line. "jcenter" is a superset of "mavenCentral", so this one it's included.

Anyway, your config should works. Try restarting your AS, and select "Clean Project" on the "Build" tab. Did you "re-sync" your Gradle file after you add the "compile" sentence?.

**Comment by taimur97** [comment]
now its wokring :) after restarting AS and cleaning the project
