### ISSUE TITLE
Folder rename

### ISSUE THREAD

**Issue by amouly** [rudsonlive/NavigationDrawer-MaterialDesign#14]
Maybe we can rename the folders on the project. The standard for this kind of project it's:

- lib/library -> not "nLiveoDrawer"
- demo/example -> not "app"

It's just a recommendation for better organization ;).

**Comment by rudsonlive** [comment]
No problem friend.

I'm still in its infancy in this world library.
If you can do this thanks.

**Comment by amouly** [comment]
I'm afraid to do this xD. The project may crash if we rename the folders :P.

**Comment by rudsonlive** [comment]
kkkkkkkkkkkkkkk

I then I do so:

app = demo
nLiveDrawer = Library

this correct?

Em Thu Jan 22 2015 at 15:47:18, Adrián Mouly <notifications@github.com>
escreveu:

**Comment by amouly** [comment]
No, do it like this:

app = demo
nLiveDrawer = library

(Lower case ever).

But please test it on another folder, don't push it until you have tested it, because it's dangerous :P.

**Comment by rudsonlive** [comment]
I will not even back up kkkkkk

I want to see the dogs in the world kkkkkkkkkk


Em Thu Jan 22 2015 at 16:07:21, Adrián Mouly <notifications@github.com>
escreveu:

**Comment by amouly** [comment]
Do you push your last changes to this repo?.

If yes, you can delete your project and download it again (that's what I did).

Or rename the directories with the old name, maybe works.

**Comment by rudsonlive** [comment]
Update github :D

Em Thu Jan 22 2015 at 16:23:46, Adrián Mouly <notifications@github.com>
escreveu:
