### ISSUE TITLE
Using only the adapter

### ISSUE THREAD

**Issue by chaimleu** [rudsonlive/NavigationDrawer-MaterialDesign#16]
There is a way to use only the adapter without use the all class?
Thanks
Haim.

**Comment by rudsonlive** [comment]
*hi*
*I'm sorry, but what you want is not possible.*

Em Sat Jan 24 2015 at 14:38:42, chaimleu <notifications@github.com>
escreveu:

**Comment by chaimleu** [comment]
OK :(, Thanks

**Comment by rudsonlive** [comment]
I explain better what is needed to meet library and your need.

Em Sat Jan 24 2015 at 15:15:29, chaimleu <notifications@github.com>
escreveu:
