### ISSUE TITLE
More than one item in footer

### ISSUE THREAD

**Issue by Hondrus** [rudsonlive/NavigationDrawer-MaterialDesign#17]
Hey! Awesome library!
How about function of adding more than one item in footer?

**Comment by rudsonlive** [comment]
Hi, how are you?

I have been doing this friend functionality. I hope to release a new update
yet this week.
Thanks for the contact.

Em Mon Jan 26 2015 at 15:29:43, Olzhas Ilyubayev <notifications@github.com>
escreveu:
