### ISSUE TITLE
diff this lib + neokree/GoogleNavigationDrawer ?

### ISSUE THREAD

**Issue by sirvon** [rudsonlive/NavigationDrawer-MaterialDesign#19]
Whats the difference between this lib 

and 

neokree/GoogleNavigationDrawer ?

**Comment by rudsonlive** [comment]
Friend did not know that library. But if you need a navigation that has a
user header my library will serve you very well.

Thanks for the contact.

Em Wed Jan 28 2015 at 16:58:15, @sirvonthomas <notifications@github.com>
escreveu:

**Comment by amouly** [comment]
@sirvon that Drawer that you mention, doesn't accomplish che Material Design rules. It's designed for Holo and android 4 styles.

**Comment by sirvon** [comment]
thx
