### ISSUE TITLE
use iconfonts/Drawables as item icon?

### ISSUE THREAD

**Issue by sirvon** [rudsonlive/NavigationDrawer-MaterialDesign#20]
How can I use drawables instead of int for the drawer icons?

I want to use iconfonts most libraries handle them as drawables not int.

**Comment by rudsonlive** [comment]
This functionality is not provided in the next version. Probably the new
version will come out this week.
Thank

Em Wed Jan 28 2015 at 19:04:55, @sirvonthomas <notifications@github.com>
escreveu:

**Comment by sirvon** [comment]
nice!
