### ISSUE TITLE
Change fragment based on selected item...

### ISSUE THREAD

**Issue by sirvon** [rudsonlive/NavigationDrawer-MaterialDesign#21]
first one thank you for your prompt communications on these issues....

How would i go about actually changing the whole fragment based on the item being selected,
instead of just sending the item's name as a variable.

```java
        FragmentManager mFragmentManager = getSupportFragmentManager();
        Fragment mFragment = new FragmentMain().newInstance(mListNameItem.get(position));
```

I want to change mFragment to say mFragment33. Is this my best bet.....

```java
        switch (position) {
            case 0:
               FragmentManager mFragmentManager = getSupportFragmentManager();
               Fragment mFragment = new FragmentMain().newInstance(mListNameItem.get(position));
               break;
            case 1:
                FragmentManager mFragmentManager = getSupportFragmentManager();
                Fragment mFragment33 = new FragmentMain().newInstance(mListNameItem.get(position));
                break;
```

**Comment by rudsonlive** [comment]
The method "onClick Navigation" returns the position of the item by
clicking on the list. Then you can create your logic and call their
fragments.
As you gave in your example the item position 1 on the list is
responsible to call the fragment33.


Em Wed Jan 28 2015 at 19:54:35, @sirvonthomas <notifications@github.com>
escreveu:
