### ISSUE TITLE
Change values in NavigationDrawer in a Fragment

### ISSUE THREAD

**Issue by PJFonseca** [rudsonlive/NavigationDrawer-MaterialDesign#24]
==PT==

Olá Rudson,

Como posso alterar aqueles números que cada opção tem mas sem ser na actividade mas sim no fragment? Basicamente porque o utilizador faz operações sobre uma RecyclerView e eu quero actualizar aquele valor na NavigationDrawer. 

Obrigado

==ENG==
Hi Rudson,

How can i change the values ( numbers ) from a fragment?

**Comment by rudsonlive** [comment]
Oi. Tudo bem?

Então. Os métodos que você pode utilizar para modificar os contadores do
Navigation são os seguintes:

/**
     * New counter value
     * @param position item position.
     * @param value new counter value.
     */
    public void setNewCounterValue(int position, int value){
        this.mNavigationAdapter.setNewCounterValue(position, value);
    }

    /**
     * Increasing counter value
     * @param position item position.
     * @param value new counter value (old value + new value).
     */
    public void setIncreasingCounterValue(int position, int value){
        this.mNavigationAdapter.setIncreasingCounterValue(position, value);
    }

    /**
     * Decrease counter value
     * @param position item position.
     * @param value new counter value (old value - new value).
     */
    public void setDecreaseCountervalue(int position, int value){
        this.mNavigationAdapter.setDecreaseCountervalue(position, value);
    }


Acredito que você pode da um cast na sua Activity que extends da
NavigationLiveo ou até mesmo criar um Listener para
acessar esses métodos na sua Activity principal.

Obrigado pelo contato amigo


Em 7 de fevereiro de 2015 13:24, PJFonseca <notifications@github.com>
escreveu:

> ==PT==
>
> Olá Rudson,
>
> Como posso alterar aqueles números que cada opção tem mas sem ser na
> actividade mas sim no fragment? Basicamente porque o utilizador faz
> operações sobre uma RecyclerView e eu quero actualizar aquele valor na
> NavigationDrawer.
>
> Obrigado
>
> ==ENG==
> Hi Rudson,
>
> How can i change the values ( numbers ) from a fragment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/24>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by PJFonseca** [comment]
Pois...isso já tenho tudo a funcionar, mas o problema está que ao clicar num botão no fragment e depois de operação de rede ( envio e recebimento de informação ) a lista é actualizada, mas gostava de puder usar o setNewCounterValue dentro de um fragment, o que estou a fazer agora é a cada "click" nas opções, e visto que tenho o switch na actividade principal, actualizo os valores de todas as opções.

Gostava de puder aceder ao metodo setNewCounterValue dentro de um fragment.

**Comment by rudsonlive** [comment]
Você pode criar uma interface dentro da sua class que extends a
NavigationLiveo
e passar essa interface para o seu fragmento e no seu fragmento vc
implementaria ela.

Em 7 de fevereiro de 2015 13:40, PJFonseca <notifications@github.com>
escreveu:

> Pois...isso já tenho tudo a funcionar, mas o problema está que ao clicar
> num botão no fragment e depois de operação de rede ( envio e recebimento de
> informação ) a lista é actualizada, mas gostava de puder usar o
> setNewCounterValue dentro de um fragment, o que estou a fazer agora é a
> cada "click" nas opções, e visto que tenho o switch na actividade
> principal, actualizo os valores de todas as opções.
>
> Gostava de puder aceder ao metodo setNewCounterValue dentro de um fragment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/24#issuecomment-73371504>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by PJFonseca** [comment]
Boa ideia! :)

Muito obrigado pela dica.
