### ISSUE TITLE
Tint background image

### ISSUE THREAD

**Issue by sciencepro** [rudsonlive/NavigationDrawer-MaterialDesign#25]
Google apps apply a tint to the background image, to make the name and email easier to read.

Any suggestions of how to do that?

**Comment by amouly** [comment]
You mean, a gradient?

**Comment by sciencepro** [comment]
Compare the two and see what I mean (same photo)

![image](https://cloud.githubusercontent.com/assets/1910066/6127668/6e5d60be-b0e2-11e4-9a2a-ccae9217b475.png)

![image](https://cloud.githubusercontent.com/assets/1910066/6127676/79a210e6-b0e2-11e4-993a-9003b341e5f7.png)

**Comment by amouly** [comment]
I see. It's like an overlay or alpha filter. Maybe applyed to the imageView. Do you have any idea? Pullrequests are welcome ;)
