### ISSUE TITLE
Animar o botão de refresh

### ISSUE THREAD

**Issue by PJFonseca** [rudsonlive/NavigationDrawer-MaterialDesign#27]
Olá Rudson,

Estou aqui a tentar animar o botão de refresh, até consegui fazer isto tudo bonito, mas ao clicar no icon ele "destroi" a actionbar.

Como posso fazer esta funcionalidade mas mantendo a tua actionbar e animar somente o icon. Posso fazer no fragment ou tenho de fazer na actividade?

Abraço

**Comment by PJFonseca** [comment]
Aqui tens um video: https://dl.dropboxusercontent.com/u/5748796/Untitled.mp4

Vale mais que mil palavras :)

**Comment by rudsonlive** [comment]
O recomendado é vc usar o SwipeRefreshLayout

https://developer.android.com/reference/android/support/v4/widget/SwipeRefreshLayout.html
