### ISSUE TITLE
how to switch between two fragment from drawer

### ISSUE THREAD

**Issue by h4h13** [rudsonlive/NavigationDrawer-MaterialDesign#31]

**Comment by h4h13** [comment]
Im using this but its not switching 
 switch (position) {
            case 0:
                mFragmentManager.beginTransaction().replace(layoutContainerId, new FragmentOthers()).commit();
            case 1:
                mFragmentManager.beginTransaction().replace(layoutContainerId, new FragmentMain()).commit();
        }

**Comment by rudsonlive** [comment]
is correct
