### ISSUE TITLE
Navigation drawer below the Actionbar

### ISSUE THREAD

**Issue by dodsont** [rudsonlive/NavigationDrawer-MaterialDesign#36]
Is there a way to make the navigation drawer not go all the way to the top of the screen?

**Comment by rudsonlive** [comment]
Friend do not understand your question. :'(

2015-03-04 13:18 GMT-03:00 dodsont <notifications@github.com>:

> Is there a way to make the navigation drawer not go all the way to the top
> of the screen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/36>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by dodsont** [comment]
I am looking use the nav drawer without the top header (background image, photo, name, email).  Also I want to still see the actionbar when the nav drawer opens.  I have found a way to remove the background image in the top header by making it not visible.  But I can't seem to remove the top header all together.

**Comment by dodsont** [comment]
I found in your layout file (navigation_main.xml) for the nav drawer it is set to full screen "android:fitsSystemWindows="true"".

I believe changing this will help solve my issue of having it not go over the actionbar.  But I am unsure how I could go about changing it.

**Comment by Talisantos** [comment]
I am very interested in can put the navigation drawer below the actionBar, If would exist a solution to customize the navigation drawer permiting set the navigationDrawer in full screen or below the ActionBar it would fantastic.

**Comment by rudsonlive** [comment]
Friend. Unfortunately it was not designed to work the way you need.

As soon as possible I will analyze a way of trying to help you.

Thanks for contact

2015-03-04 16:27 GMT-03:00 Iván Santos <notifications@github.com>:

> I am very interested in can put the navigation drawer below the actionBar,
> If would exist a solution to customize the navigation drawer permiting set
> the navigationDrawer in full screen or below the ActionBar it would
> fantastic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/36#issuecomment-77227749>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by dodsont** [comment]
You have a function called removeDefaultHeader() inside of the main class.  It is the only one that is private.  I think if you make this public it would allow us to remove that top header.

To solve the other request (having a nav drawer that is not full screen) if you can make access to mDrawerLayout public, we will be able to toggle the Boolean for full screen or not.

Thank You.

**Comment by rudsonlive** [comment]
Now you can remove the header in version 2.3.2

Use .removeHeader() method

**Comment by aadhk** [comment]
extends NavigationActionBarLiveo

**Comment by klever34** [comment]
android:layout_marginTop="@dimen/abc_action_bar_default_height_material"
