### ISSUE TITLE
Item de menu ativo após rotação da tela

### ISSUE THREAD

**Issue by waister** [rudsonlive/NavigationDrawer-MaterialDesign#38]
Rudson, quando eu seleciono um item no menu e depois rotaciono o aparelho, o item selecionado volta pro default. Tipo que a activity foi recriada e perdeu as ações do usuário.
Tem como ver se no seu fica com esse problema, porquê talvez eu tenha feito algo de errado.
Obrigado!

**Comment by rudsonlive** [comment]
Olá Waister tudo bem?

Obrigado pelo seu contato e espero que minha biblioteca esteja lhe ajudando.

Acredito que você esteja utilizando o método
this.setDefaultStartPositionNavigation(int position) não é isso?

Coloca a seguinte verificação que lhe garanto que vai correr tudo como você
quer.

        if (savedInstanceState == null) {
            //First item of the position selected from the list
            this.setDefaultStartPositionNavigation(1);
        }

 Obrigado

Em 10 de março de 2015 11:38, Waister Nunes <notifications@github.com>
escreveu:

> Rudson, quando eu seleciono um item no menu e depois rotaciono o aparelho,
> o item selecionado volta pro default. Tipo que a activity foi recriada e
> perdeu as ações do usuário.
> Tem como ver se no seu fica com esse problema, porquê talvez eu tenha
> feito algo de errado.
> Obrigado!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/38>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by waister** [comment]
Era isso mesmo, valeu demais pela ajuda.
