### ISSUE TITLE
Import project : gradle issues

### ISSUE THREAD

**Issue by anthony-skr** [rudsonlive/NavigationDrawer-MaterialDesign#4]
Hello,

I faced some issues when importing this Git project to Android studio.

*NavigationDrawerMaterialDesign/nLiveoDrawer/build.gradle*

* I had gradle error about this : 

```
uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: "https://oss.sonatype.org/content/repositories/snapshots")
            pom.groupId = GROUP
            pom.artifactId = POM_ARTIFACT_ID
            pom.version = VERSION_NAME
        }
    }
}
```
Not able to find GROUP, so I commented this part and it imported it fine.

* After, gradle build has failed because of : 
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
}
```
Gradle was not able to find 21.0.3 version, but it works with 21.0.+

That's it, just wanted to share my experience :)

Thanks,
Anthony

**Comment by rudsonlive** [comment]
Thanks for the feedback.

This information on the group was not to be there: D.

What about the version of 21.0.3 believe you have to update your SDK.

Thanks again for the contact.

2015-01-15 15:13 GMT-03:00 Anthony Skrzypczyk <notifications@github.com>:

> Hello,
>
> I faced some issues when importing this Git project to Android studio.
>
> *NavigationDrawerMaterialDesign/nLiveoDrawer/build.gradle*
>
>    - I had gradle error about this :
>
> uploadArchives {
>     repositories {
>         mavenDeployer {
>             repository(url: "https://oss.sonatype.org/content/repositories/snapshots")
>             pom.groupId = GROUP
>             pom.artifactId = POM_ARTIFACT_ID
>             pom.version = VERSION_NAME
>         }
>     }
> }
>
> Not able to find GROUP, so I commented this part and it imported it fine.
>
>    - After, gradle build has failed because of :
>
> dependencies {
>     compile fileTree(dir: 'libs', include: ['*.jar'])
>     compile 'com.android.support:appcompat-v7:21.0.3'
> }
>
> Gradle was not able to find 21.0.3 version, but it works with 21.0.+
>
> That's it, just wanted to share my experience :)
>
> Thanks,
> Anthony
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/4>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
