### ISSUE TITLE
Subheader color and letter

### ISSUE THREAD

**Issue by GerardSoleCa** [rudsonlive/NavigationDrawer-MaterialDesign#40]
Hi,

I'm trying to set some subheaders, put when I configure them they appear like normal items, the only difference is that I can't click on them.

What should I do to make them look like yours? (aka + Markers)

Thanks for this library!

**Comment by rudsonlive** [comment]
To say that the item is a subheader you just create it and inform the
adapter

//Name subHeader
mListNameItem.add(4, getString(R.string.more_markers)); //This item will be
a subHeader

//{optional} - Among the names there is some subheader, you must indicate
it here
List<Integer> mListHeaderItem = new ArrayList<>();
mListHeaderItem.add(4);

If want a subheader with only one line and no text, just put empty arrays
mListNameItem.add(4, ""); //This item will be a subHeader

2015-03-21 17:04 GMT-03:00 Gerard <notifications@github.com>:

> Hi,
>
> I'm trying to set some subheaders, put when I configure them they appear
> like normal items, the only difference is that I can't click on them.
>
> What should I do to make them look like yours? (aka + Markers)
>
> Thanks for this library!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/40>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
