### ISSUE TITLE
Imagens sombreadas na lista de opções

### ISSUE THREAD

**Issue by filipimosquini** [rudsonlive/NavigationDrawer-MaterialDesign#42]
Olá Rudson,

Ao criar um List de ícones para a lista de opções da navigation drawer as imagens aparecem sombreadas sendo que são coloridas. O mesmo comportamento não ocorre quando carrego as imagens no método setFooterInformationDrawer, neste método as imagens são carregadas normalmente.

Existe alguma outra forma para carregar essas imagens da lista de opções?

![capturar](https://cloud.githubusercontent.com/assets/5280221/6925179/0b79ed7a-d7b4-11e4-8d2b-507573b23753.PNG)

**Comment by rudsonlive** [comment]
Their images are custom, you can use the .removeColorFilter() method, so your images will have changed their fill.
