### ISSUE TITLE
Material Tabs and this lib

### ISSUE THREAD

**Issue by leighayanid** [rudsonlive/NavigationDrawer-MaterialDesign#44]
How can I implement material sliding tabs together with this lib? I need to use onCreate for viewpager and adapter, any alternative method? Where should I put them?

**Comment by rudsonlive** [comment]
I made this sample project using the navigation library. I believe that is
what you seek.

https://github.com/rudsonlive/NavigationDrawerViewPage-MaterialDesign

**Comment by leighayanid** [comment]
exactly what I need. Thanks :+1:
