### ISSUE TITLE
change title text color and drawer icon color

### ISSUE THREAD

**Issue by cl0ud9** [rudsonlive/NavigationDrawer-MaterialDesign#46]
How can i change the color of the title textcolor and drawer icon color?

**Comment by rudsonlive** [comment]
These are all color related methods.
I hope one of them will help you.

thank you


public void setColorIconItemNavigation(int colorId){}
   public void setColorNameItemNavigation(int colorId){}
   public void setFooterInformationDrawer(String title, int icon, int
colorName, int colorIcon){}
   public void setFooterInformationDrawer(int title, int icon, int
colorName, int colorIcon){}

public void setColorSeparatorItemSubHeaderNavigation(int colorId){}
    public void setNewName(int position, String name){}
    public void setNewName(int position, int name){}
    public void setNewIcon(int position, int icon){}
    public void setNewInformationItem(int position, int name, int
icon, int counter){}
    public void setNewInformationItem(int position, String name, int
icon, int counter){}


2015-04-13 7:37 GMT-03:00 cl0ud9 <notifications@github.com>:

> How can i change the color of the title textcolor and drawer icon color?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/46>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
