### ISSUE TITLE
Setting back arrow in action bar

### ISSUE THREAD

**Issue by Noezis** [rudsonlive/NavigationDrawer-MaterialDesign#47]
First of all, thanks for great library!

I'd like to make master/detail flow in my app and show back arrow after setting new child fragment. 

            mFragmentManager.beginTransaction()
                    .replace(layoutContainerId, mFragment)
                    .addToBackStack("test")
                    .commit();

        // here show back arrow in actionbar

Is it possible using this library?

**Comment by ppamorim** [comment]
No, because Toolbar don't have a method for this.
