### ISSUE TITLE
Color of the counting numbers

### ISSUE THREAD

**Issue by PJFonseca** [rudsonlive/NavigationDrawer-MaterialDesign#48]
-- Em Português--

Olá Rudson,

Como posso mudar a cor dos contadores? É que agora com a nova versão, a cor está branca, a mesma que o fundo. Só se consegue ver quando está seleccionado.

Obrigado

--In English--
Hi Rudson,

How can i change the CounterItem color? With this new version it stays white, has the backgourd of the navigation.

![screenshot_2015 04 25 08 40 34](https://cloud.githubusercontent.com/assets/3879175/7332145/9091528c-eb28-11e4-9146-b23ccedf8ef1.png)

**Comment by rudsonlive** [comment]
Obrigado pelo contato.

Irei verificar isso e corrigir.

Isso está acontecendo com a versão 1.0.5?

Se realmente estiver acontecendo isso hoje mesmo já lanço uma nova versão e
com a possibilidade de mudar a cor do contador.

Obrigado.

**Comment by PJFonseca** [comment]
Sim é na última versão.

**Comment by rudsonlive** [comment]
OK. Ate ao meio dia de hoje terá uma nova versão a 2.0.

Obrigado amigo.

**Comment by PJFonseca** [comment]
Ora essa. Eu é que agradeço.

**Comment by rudsonlive** [comment]
Você usou alguns dos métodos pra personalizar a cor dos itens?

Pois pode ser algum conflito.

Agora lembrei que um amigo me falou que teve problema com cores nos
TextView usando a nova AppCompatActivity.

Mas valeu pelo retorno.

A lib tem lhe ajudado bem? Pelo o pouco que da pra ver seu app ta bonito :D

**Comment by rudsonlive** [comment]
Aqui não acontece o problema que vc relatou.

Qual aparelho e versão vc está utilizando?

**Comment by PJFonseca** [comment]
Não usei cores nenhumas, estás tudo por defeito. Estou a usar android 4.2.1 num Wiko DarkFull.

Já estive a ver se podia ter sido alguma coisa nas cores, mas não. Está tudo por defeito e deixo a sua Lib tratar das cores.

**Comment by PJFonseca** [comment]
Rudson,

Mil desculpas, como actualizei para o novo appcompact isto ficou tudo doido com cores e tal. O problema não é a sua Lib. 

Uma vez mais, peço desculpa.
