### ISSUE TITLE
No transparent status bar in Android 4.4

### ISSUE THREAD

**Issue by anticafe** [rudsonlive/NavigationDrawer-MaterialDesign#5]
I install your app from Google Play on my Galaxy S4 (running Android 4.4) but see the black status bar instead of transparent.

![image](https://cloud.githubusercontent.com/assets/340836/5788344/58e8dff2-9e62-11e4-96e6-e9068c204724.png)

Is the transparent status bar only support in Android 5.0?

**Comment by rudsonlive** [comment]
Yes friend.

Transparency only the API 21 up.

Google recommends follow the pattern of each api so be not custumizei the
statusbar for smaller versions to 21.

Thanks for the contact.

2015-01-17 6:04 GMT-03:00 anticafe <notifications@github.com>:

> I install your app from Google Play on my Galaxy S4 (running Android 4.4)
> but see the black status bar instead of transparent.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/340836/5788344/58e8dff2-9e62-11e4-96e6-e9068c204724.png>
>
> Is the transparent status bar only support in Android 5.0?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/5>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by anticafe** [comment]
OK I see.

But according to [Android Kitkat document](http://developer.android.com/about/versions/android-4.4.html#UI), from Android 4.4, there is a `Translucent system bars`. So is your transparent status bar is different from Kitkat's translucent system bar?

**Comment by rudsonlive** [comment]
They are different things yes.

If you look not to own Google did it in their apps updates as gmail, google
play and etc ..

2015-01-17 9:58 GMT-03:00 anticafe <notifications@github.com>:

> OK I see.
>
> But according to Android Kitkat document
> <http://developer.android.com/about/versions/android-4.4.html#UI>, from
> Android 4.4, there is a Translucent system bars. So is your transparent
> status bar is different from Kitkat's translucent system bar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/5#issuecomment-70366102>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by anticafe** [comment]
Hmm, thank for your notice.

Last time I wonder why install Google apps such as Gmail, Play Store... on my phone (Android 4.4) but no transparent status bar. Now I understand why :)
