### ISSUE TITLE
What is the origin of layoutContainerId?

### ISSUE THREAD

**Issue by jhonvidal** [rudsonlive/NavigationDrawer-MaterialDesign#50]
What is the origin of layoutContainerId?

to call the R.id.?, from a button event

```java
@Override //The "layoutContainerId" should be used in "beginTransaction (). Replace"
    public void onItemClickNavigation(int position, int layoutContainerId) {

        FragmentManager mFragmentManager = getSupportFragmentManager();
        Fragment mFragment = new FragmentMain().newInstance(mListNameItem.get(position));

        if (mFragment != null){
            mFragmentManager.beginTransaction().replace(layoutContainerId, mFragment).commit();
        }
    }
```

```java
        button_bt_count_clientes.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                MainActivity mainActivity = (MainActivity) getActivity();
                mainActivity.onItemClickNavigation(1, layoutContainerId); //layoutContainerId = ? , R.id. ?????? please it belongs to the library
            }
        });
```

**Comment by rudsonlive** [comment]
The library already has a FrameLayout so that you do not need to create
one. Then all the fragments go the one that replace FrameLayout. In which
case I return his ID attribute that I called layoutContainerId.

No onItemClickNavigation eu sempre retorno a posição clicada na lista e o
id do FrameLayout.

2015-05-18 10:32 GMT-03:00 Jhon Ramiro Vidal Alvarez <
notifications@github.com>:

> What is the origin of layoutContainerId?
>
> to call the R.id.?, from a button event
>
> @Override //The "layoutContainerId" should be used in "beginTransaction (). Replace"
>     public void onItemClickNavigation(int position, int layoutContainerId) {
>
>         FragmentManager mFragmentManager = getSupportFragmentManager();
>         Fragment mFragment = new FragmentMain().newInstance(mListNameItem.get(position));
>
>         if (mFragment != null){
>             mFragmentManager.beginTransaction().replace(layoutContainerId, mFragment).commit();
>         }
>     }
>
>         button_bt_count_clientes.setOnClickListener(new View.OnClickListener() {
>             @Override
>             public void onClick(View v) {
>                 MainActivity mainActivity = (MainActivity) getActivity();
>                 mainActivity.onItemClickNavigation(1, layoutContainerId); //layoutContainerId = ? , R.id. ?????? please it belongs to the library
>             }
>         });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/50>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by jhonvidal** [comment]
when you start the app I need layoutContainerId code to change layout from another component.

Ie fragments change without relying on the menu list.

**Comment by rudsonlive** [comment]
Understands your situation.

What you can do today is to keep this ID, as when the application is first
started, the onItemClickNavigation method is called automatically.

Soon will be released a new update and to help you have will provide this
ID behind a method.

Thank you for the contact.

2015-05-18 10:51 GMT-03:00 Jhon Ramiro Vidal Alvarez <
notifications@github.com>:

> when you start the app I need layoutContainerId code to change layout from
> another component.
>
> Ie fragments change without relying on the menu list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/50#issuecomment-103067093>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by jhonvidal** [comment]
thanks for the help, and I found the solution:

```java
 // R.id.container from the library
   MainActivity mainActivity = (MainActivity) getActivity();
        mainActivity.onItemClickNavigation(1, R.id.container);

```

:sunglasses:   :satisfied:

**Comment by rudsonlive** [comment]
Putz kkkkkkkkkkkkk

Forget what you already have access to library ID :D

Good boy.

2015-05-18 11:12 GMT-03:00 Jhon Ramiro Vidal Alvarez <
notifications@github.com>:

> thanks for the help, and I found the solution:
>
>  // R.id.container from the library
>    MainActivity mainActivity = (MainActivity) getActivity();
>         mainActivity.onItemClickNavigation(1, R.id.container);
>
> [image: :sunglasses:] [image: :satisfied:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/50#issuecomment-103072266>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
