### ISSUE TITLE
Minimum SDK requirement 

### ISSUE THREAD

**Issue by devrath** [rudsonlive/NavigationDrawer-MaterialDesign#52]
Min-SDK requirement can be 10 ... Is it possible in this project demo ?

**Comment by rudsonlive** [comment]
Friend unfortunately today is not possible for this release date
limitations.

If lever into account this graph
<https://developer.android.com/about/dashboards/index.html> you can see
that it is not worth investing in smaller api than 16.

Thank you for the contact.

2015-05-19 8:25 GMT-03:00 Devrath <notifications@github.com>:

> Min-SDK requirement can be 10 ... Is it possible in this project demo ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/52>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by devrath** [comment]
Ok, Thank you for the info :)
