### ISSUE TITLE
Header height.

### ISSUE THREAD

**Issue by RokasAug** [rudsonlive/NavigationDrawer-MaterialDesign#53]
Hello, 

How to properly remove header from the drawer? this.removeCustomHeader(View v)? But what should I put in "View v"? 

And is it possible to change header's height? 

Thank you!
@hussanhijazi 
@amouly 
@rudsonlive 
@Ashwinvalento

**Comment by rudsonlive** [comment]
Look if it can help you friend. NavigationActionBarLiveo
<https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/blob/master/README.md#navigationactionbarliveo>


2015-05-29 12:29 GMT-03:00 RokasAug <notifications@github.com>:

> Hello,
>
> How to properly remove header from the drawer?
> this.removeCustomHeader(View v)? But what should I put in "View v"?
>
> And is it possible to change header's height?
>
> Thank you!
> @hussanhijazi <https://github.com/hussanhijazi>
> @amouly <https://github.com/amouly>
> @rudsonlive <https://github.com/rudsonlive>
> @Ashwinvalento <https://github.com/Ashwinvalento>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/53>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by RokasAug** [comment]
I have read the readme. But there's not much of information. There's no method ".removeHeader()". There's only ".removeCustomHeader(View v)" and what should I put in View?

**Comment by RokasAug** [comment]
Ohh.. I'm using very old version, sorry. :)

**Comment by rudsonlive** [comment]
It is because you are using the NavigationLiveo friend, use please
NavigationActionBarLiveo.

2015-05-29 12:50 GMT-03:00 RokasAug <notifications@github.com>:

> Ohh.. I'm using very old version, sorry. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/53#issuecomment-106854231>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by RokasAug** [comment]
And what's the difference between them?

**Comment by rudsonlive** [comment]
The difference is that the side menu of NavigationActionbar is below the
toolbar and not above it as with NavigationLiveo apart from that everything
one does the other does.

I am at the moment implementing the RemoveHeader of NavigationLiveo method
and believe that tomorrow I will have available the new version.

Outside this difference
Thank you.

**Comment by RokasAug** [comment]
Cool! Thank you!
