### ISSUE TITLE
Drawer background, seperators and text colour.

### ISSUE THREAD

**Issue by RokasAug** [rudsonlive/NavigationDrawer-MaterialDesign#54]
Hello,

How could I change drawer background, seperators and text colour?

Thank you!

@hussanhijazi 
@amouly 
@rudsonlive 
@Ashwinvalento

**Comment by rudsonlive** [comment]
In the demo project you will find these features, it's just you remove
those discussed methods and see the result.

Everything will depend on your creativity: D

.selectorCheck(R.drawable.selector_check)

.colorItemDefault(R.color.nliveo_blue_colorPrimary)
.colorItemSelected(R.color.nliveo_purple_colorPrimary)
.backgroundList(R.color.nliveo_black_light)
.colorLineSeparator(R.color.nliveo_transparent)
