### ISSUE TITLE
Tabs are fiting in the screen

### ISSUE THREAD

**Issue by rodrigokiller** [rudsonlive/NavigationDrawer-MaterialDesign#58]
My tabs is not scrolling through the screen: all the tabs are grouping to fit the screen.
Take a look 
![screenshot_2015-06-17-20-49-12](https://cloud.githubusercontent.com/assets/1853922/8221292/0d2689b4-1533-11e5-8981-07634d394606.png)

Thats is how i want to do
![screenshot_2015-06-17-20-49-56](https://cloud.githubusercontent.com/assets/1853922/8221298/1d4ce054-1533-11e5-805c-8ca3b5ef6cc0.png)

**Comment by rudsonlive** [comment]
You should friend is using the fixed tabmode.
remove it or change the value.

2015-06-17 20:55 GMT-03:00 Rodrigo Sanguanini <notifications@github.com>:

> My tabs is not scrolling through the screen: all the tabs are grouping to
> fit the screen.
> Take a look
> [image: screenshot_2015-06-17-20-49-12]
> <https://cloud.githubusercontent.com/assets/1853922/8221292/0d2689b4-1533-11e5-8981-07634d394606.png>
>
> Thats is how i want to do
> [image: screenshot_2015-06-17-20-49-56]
> <https://cloud.githubusercontent.com/assets/1853922/8221298/1d4ce054-1533-11e5-805c-8ca3b5ef6cc0.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/58>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by rodrigokiller** [comment]
Thats the point, i cant find where to set the tabmode to scrollable

**Comment by rudsonlive** [comment]
You are using the TabLayout of Design Support Library?

If she utlizando you make this change in xml or java.

xml = app:tabmod
Java = setTabMode


2015-06-17 21:12 GMT-03:00 Rodrigo Sanguanini <notifications@github.com>:

> Thats the point, i cant find where to set the tabmode to scrollable
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/58#issuecomment-112984150>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by rodrigokiller** [comment]
Thank you.
Im new in this thing. 
I was looking at this setting (tabMode). I put that in the xml and set this to scrollable and that works fine.
