### ISSUE TITLE
Background image and list bug

### ISSUE THREAD

**Issue by kriskast** [rudsonlive/NavigationDrawer-MaterialDesign#59]
Hi, firstly thanks for this awesome library.

I am testing my app and noticed then when the app is opened on a tablet the first item in the drawer list loses it text but keeps its drawable (doesn't seem to be happening on phones) as seen in the attached image.

![4a0b2c0ec75470e5960de66bdabdf753 1](https://cloud.githubusercontent.com/assets/12373559/8235448/52e62342-15e2-11e5-8edc-312245d4026c.png)

Also what would you recommend so the top background image doesn't stretch? As it appears right on some devices and stretched on others.

Regards,
Chris

**Comment by rudsonlive** [comment]
Friend, use the latest version as this bug has been fixed: D.

compile 'br.com.liveo:navigationdrawer-material:2.3.3'

E About the image I would have to analyze the best way. But you can test
using the method this.userBackground.setScaleType (ScaleType); Thank you
for contact.


2015-06-18 12:49 GMT-03:00 kriskast <notifications@github.com>:

> Hi, firstly thanks for this awesome library.
>
> I am testing my app and noticed then when the app is opened on a tablet
> the first item in the drawer list loses it text but keeps its drawable
> (doesn't seem to be happening on phones) as seen in the attached image.
>
> [image: 4a0b2c0ec75470e5960de66bdabdf753 1]
> <https://cloud.githubusercontent.com/assets/12373559/8235448/52e62342-15e2-11e5-8edc-312245d4026c.png>
>
> Also what would you recommend so the top background image doesn't stretch?
> As it appears right on some devices and stretched on others.
>
> Regards,
> Chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/59>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by kriskast** [comment]
Thanks for the reply, I did that however it just crashed the app (see below), to fix it i added these to my theme:

<item name="windowActionBar">false</item>
<item name="windowNoTitle">true</item>

I posted this so others may see it.

Thanks again for the library :D

**Comment by rudsonlive** [comment]
I'm very happy to help.

Thank you and success.

2015-06-18 13:13 GMT-03:00 kriskast <notifications@github.com>:

> Thanks for the reply, I did that however it just crashed the app (see
> below), to fix it i added these to my theme:
>
> false
> true
>
> I posted this so others may see it.
>
> Thanks again for the library :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/59#issuecomment-113205634>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
