### ISSUE TITLE
Problem adding custom header

### ISSUE THREAD

**Issue by hugoM1** [rudsonlive/NavigationDrawer-MaterialDesign#6]
I'm trying to use the library but I can't have access to this method and I can't set a custom header for the NavigationDrawer. Thanks for your help.

@Override
    public void onUserInformationCustomHeader() {
        mCustomHeader = getLayoutInflater().inflate(R.layout.custom_header_user, this.getListView(), false);

        TextView textview = (TextView) mCustomHeader.findViewById(R.id.textview);
        textview.setOnClickListener(onClick);
        this.addCustomHeader(mCustomHeader);
    }

**Comment by rudsonlive** [comment]
This functionality will only be version 1.2.0. I still have to do more
tests before finalizing this version. If you can test this functionality
using the sources thank

**Comment by rudsonlive** [comment]
Good evening.

Now you can add a header custom user in version 1.0.2. Should resoltar that this version is now with MinSDK 14 then its 8 as in previous versions.

Hope that helps you. And please do not forget to close this issue

**Comment by hoshomoh** [comment]
Thanks for the information.

On Tue, Jan 20, 2015 at 5:03 AM, Rudson Lima <notifications@github.com>
wrote:

> Good evening.
>
> Now you can add a header custom user in version 1.0.2. Should resoltar
> that this version is now with MinSDK 14 then its 8 as in previous versions.
>
> Hope that helps you. And please do not forget to close this issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/6#issuecomment-70601490>
> .
>



-- 

  Thanks.

  Best Regards


*Oforomeh Oshomo*
Application Developer

+2348121154813
dave@wildfusions.com <chidi@wildfusions.com>
www.wildfusions.com

[image: Description: Macintosh HD:Users:wildfusion:Documents:WildFusion
Footer:images:WF_Footer_07.png]
*Wild Fusion Nigeria*
205A Corporation Drive, Dolphin Estate, Ikoyi, Lagos.
*t:* +234-1-2914474

*Wild Fusion Ghana*
Essar Business Center, F521/1 Fifth Lane, Osu, Accra, Ghana.
 *t: *+233-342196302


*Wild Fusion Kenya*
Riverside Studios, Riverside Lane, Off Riverside Drive, Nairobi, Kenya.
*t:* +254 20 2664480


*[image: Description: Macintosh HD:Users:wildfusion:Documents:WildFusion
Footer:images:WF_Footer_03.png]*



[image: Description: Macintosh HD:Users:wildfusion:Documents:WildFusion
Footer:images:WF_Footer_13.gif] <https://twitter.com/Wildfusion> [image:
Description: Macintosh HD:Users:wildfusion:Documents:WildFusion
Footer:images:WF_Footer_15.gif]
<https://www.facebook.com/Wildfusionltd> [image:
Description: Macintosh HD:Users:wildfusion:Documents:WildFusion
Footer:images:WF_Footer_17.gif]
<https://www.linkedin.com/company/wild-fusion-limited?trk=top_nav_home>
This message contains confidential information and is intended solely for
the use of the individual or entity to whom it is addressed. If you are not
the named addressee you should not disseminate, distribute or copy this
e-mail. If you have received this e-mail in error, please notify the sender
immediately and delete from your system. While we have taken every
reasonable precaution to ensure that no viruses or malicious code are
present in this e-mail or in any associated attachments, we cannot accept
responsibility for any loss or damage arising from the use of this e-mail
or attachments. Additionally, any views or opinions expressed in this
e-mail are solely those of the author and do not necessarily represent
those of Wild Fusion.

**Comment by rudsonlive** [comment]
I hope make this available in the next version friend.

It's a little complicated because they are several layout and am bucando do more simply to developers who are using the library does not have any work.

Thanks for the contact.
