### ISSUE TITLE
Custom header bar?

### ISSUE THREAD

**Issue by dinhhieuac** [rudsonlive/NavigationDrawer-MaterialDesign#61]
Hi,dev.Thanks for your awesome library
I can add a custom header bar
![capture1](https://cloud.githubusercontent.com/assets/1254967/8322770/c7361564-1a64-11e5-98ef-14ac6255182a.PNG)
thanks dev

**Comment by rudsonlive** [comment]
I never made a safe test, but I tried to use it.

this.getToolbar () addView (You anger inform the layout of your custom toolbar.);
