### ISSUE TITLE
addSubHeader() with counter

### ISSUE THREAD

**Issue by DanielAccorsi** [rudsonlive/NavigationDrawer-MaterialDesign#62]
Hi people!!

You can include a counter in addSubHeader () just as there is in add (). Very useful to group the count of all items.

Thanks for now! ;)

**Comment by rudsonlive** [comment]
Very interesting idea his friend.

I will analyze this new functionality and so launches a new version you
notice.

Very orbigado by contact.

2015-07-02 11:34 GMT-03:00 Daniel Accorsi <notifications@github.com>:

> Hi people!!
>
> You can include a counter in addSubHeader () just as there is in add ().
> Very useful to group the count of all items.
>
> Thanks for now! ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/62>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by rudsonlive** [comment]
Sorry for the delay.

I put this functionality in version 2.4.

Thanks for the tip.
