### ISSUE TITLE
Dialog Text color

### ISSUE THREAD

**Issue by kriskast** [rudsonlive/NavigationDrawer-MaterialDesign#65]
Hi is there any reason why in dialogs the text appears white in the nLiveo.Theme.DarkActionBar theme?
![screenshot_2015-07-06-12-19-33](https://cloud.githubusercontent.com/assets/12373559/8520317/5b15f43e-23d9-11e5-864e-dedafea946f2.png)

**Comment by kriskast** [comment]
Also do you think it will be possible to add 
nLiveo.Theme.Light.DarkActionBar ?

**Comment by rudsonlive** [comment]
Use this version here.
Thanks.

compile 'br.com.liveo:navigationdrawer-material:2.3.4'
