### ISSUE TITLE
Reduce User Information size

### ISSUE THREAD

**Issue by harishannam** [rudsonlive/NavigationDrawer-MaterialDesign#67]
Is there a way to set the height of the user info area? I removed the user profile picture and there is a lot of empty space left which I want to remove.

**Comment by rudsonlive** [comment]
Hello.

Friend you can create a custom header.

requirements

1 - Use the version 2.3.4

compile 'br.com.liveo:navigationdrawer-material:2.3.4'

2 - Create your header layout

View mCustomHeader =
getLayoutInflater().inflate(R.layout.custom_header_user,
this.getListView(), false);
ImageView imageView = (ImageView) mCustomHeader.findViewById(R.id.imageView);

3 - Use the CustomHeader method and inform the view of your layout

.customHeader(mCustomHeader)


In MainActivity
<https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/blob/master/demo/src/main/java/br/liveo/ndrawer/ui/activity/MainActivity.java>
class demo project has a commented example.

I hope it helps you.

Thank you for the contact


2015-07-15 4:33 GMT-03:00 Harish Annam <notifications@github.com>:

> Is there a way to set the height of the user info area? I removed the user
> profile picture and there is a lot of empty space left which I want to
> remove.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/67>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
