### ISSUE TITLE
Get Actionbar and Toolbar instance.

### ISSUE THREAD

**Issue by filipimosquini** [rudsonlive/NavigationDrawer-MaterialDesign#68]
hi devs.
How i get actionbar and toolbar instance?
I use the compile 2.3.4 and the methods  this.getSupportActionBar() and this.getToolbar() returns null. On previous versions i could work with this methods without problems.

**Comment by rudsonlive** [comment]
I believe that you are using before the method "with".

If you look in the class MainActivity the demo project, I directory to use
the method "setElevationToolBar" and he use "getToolbar ()" and is running
smoothly.

Checks for me if you are really using before the method "with" please.

Thank you for contact.

2015-07-16 11:39 GMT-03:00 filipimosquini <notifications@github.com>:

> hi devs.
> How i get actionbar and toolbar instance?
> I use the compile 2.3.4 and the methods this.getSupportActionBar() and
> this.getToolbar() returns null. On previous versions i could work with this
> methods without problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/68>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by filipimosquini** [comment]
I put this methods after the "with" and worked.
Thank you for attention.

**Comment by rudsonlive** [comment]
I thank you my friend.

Thank you for contact: D

2015-07-16 15:16 GMT-03:00 filipimosquini <notifications@github.com>:

> I put this methods after the "with" and worked.
> Thank you for attention.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/68#issuecomment-122039564>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
