### ISSUE TITLE
how should I show a Menu in Main ui

### ISSUE THREAD

**Issue by 1252768410** [rudsonlive/NavigationDrawer-MaterialDesign#7]
Now in my MainActivity,I override the method onCreateOptionsMenu (like follow) but I can't watch menu,how should I do , thanks

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.main_menu,menu);
        return super.onCreateOptionsMenu(menu);
    }

**Comment by 1252768410** [comment]
Maybe I went wrong , Now it start to work ！

**Comment by rudsonlive** [comment]
Thanks for the contact.

I just did a test here and to use menu is only declares the
"onCreateOptionsMenu" and ignite the menu layout is done in a normal
Activity.

Now remembering that usually the class where you find the drawlayout
usually has no menu for making this process are the fragments.

I hope that my project is helping you and any problem can contact me.

Thank U

2015-01-18 7:32 GMT-03:00 GuDong <notifications@github.com>:

> Maybe I went wrong , Now it start to work ！
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/7#issuecomment-70403146>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by rudsonlive** [comment]
If you are all right, when you can close this issue.

Thank.
