### ISSUE TITLE
Show New Fragments

### ISSUE THREAD

**Issue by melihcolpan** [rudsonlive/NavigationDrawer-MaterialDesign#71]
Hello Friend,

I added new fragments and I cannot see search and add button on actionbar. 
I changed ViewPagerAdapter's method like that and I returned new fragments:

@Override
    public Fragment getItem(int i) {
       switch (i) {
            case 0:
                return new FragmentNow();
            case 1:
                return new FragmentHourly();
            case 2:
                return new FragmentDays();
        }
}

**Comment by rudsonlive** [comment]
You must implement the menu in fragments.

2015-08-03 5:34 GMT-03:00 Melih Çolpan <notifications@github.com>:

> Hello Friend,
>
> I added new fragments and I cannot see search and add button on actionbar.
> I changed ViewPagerAdapter's method like that and I returned new fragments:
>
> @Override <https://github.com/Override>
> public Fragment getItem(int i) {
> switch (i) {
> case 0:
> return new FragmentNow();
> case 1:
> return new FragmentHourly();
> case 2:
> return new FragmentDays();
> }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/71>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
