### ISSUE TITLE
Adding another footer item

### ISSUE THREAD

**Issue by mohansainani** [rudsonlive/NavigationDrawer-MaterialDesign#72]
Hi  Friend,
I tried adding another footer item.
like

 with(this).startingPosition(2) //Starting position in the list
                .addAllHelpItem(mHelpLiveo.getHelp())
                .footerItem(R.string.aboutus, R.mipmap.ic_aboutus_black_24dp)
                .setOnClickUser(onClickPhoto)
                .setOnPrepareOptionsMenu(onPrepare)
                .setOnClickFooter(onClickFooter)
                .build();

this doesn't work kindly help me how to add another footer item and implementing onclick of footer seperately...Thanks in advance

Thanks.....

**Comment by rudsonlive** [comment]
Hello.
Friend, unfortunately today is not possible to have two wheel, but I will
evaluate this option and maybe next update, this functionality is now
available.

Thank you for the contact.

2015-08-10 3:23 GMT-03:00 mohansainani <notifications@github.com>:

> Hi I tried adding another footer item.
> like
>
> with(this).startingPosition(2) //Starting position in the list
> .addAllHelpItem(mHelpLiveo.getHelp())
> .footerItem(R.string.aboutus, R.mipmap.ic_aboutus_black_24dp)
> .setOnClickUser(onClickPhoto)
> .setOnPrepareOptionsMenu(onPrepare)
> .setOnClickFooter(onClickFooter)
> .build();
>
> this doesn't work kindly help me how to add another footer item and
> implementing onclick of footer seperately...Thanks in advance
>
> Thanks.....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/72>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by johngamarra** [comment]
+1 this for next update

**Comment by Aeonia** [comment]
Can we now have two footer items?

**Comment by rudsonlive** [comment]
Yes.

You can use footerSecondItem. To learn more just look the methods whose
initials "footerSecond".
Thank you.


2015-11-30 6:37 GMT-03:00 Aeonia <notifications@github.com>:

> Can we now have two footer items?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/72#issuecomment-160573810>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
