### ISSUE TITLE
Rtl support?

### ISSUE THREAD

**Issue by TheLoyalCruel** [rudsonlive/NavigationDrawer-MaterialDesign#75]
does it support Right to left?

**Comment by rudsonlive** [comment]
Unfortunately no friend.

Thank you for the contact.

2015-09-16 8:51 GMT-03:00 Mohsen Shafiee <notifications@github.com>:

> does it support Right to left?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/75>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by TheLoyalCruel** [comment]
thanks for this library :)

**Comment by rudsonlive** [comment]
I thank you :D

2015-09-16 8:55 GMT-03:00 Mohsen Shafiee <notifications@github.com>:

> thanks for this library :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/75#issuecomment-140719611>
> .
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
