### ISSUE TITLE
How to override navigation_list_item.xml

### ISSUE THREAD

**Issue by beydogan** [rudsonlive/NavigationDrawer-MaterialDesign#77]
I want to add custom stuff to navigation_list_item.xml. Is there a way to override it?

**Comment by rudsonlive** [comment]
Today unfortunately no friend.

I apologize for that.

2015-10-02 9:15 GMT-03:00 Mehmet Beydogan <notifications@github.com>:

> I want to add custom stuff to navigation_list_item.xml. Is there a way to
> override it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/77>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>

**Comment by beydogan** [comment]
Is there a way you can suggest so I can implement it by myself?
