### ISSUE TITLE
Toolbar textColor

### ISSUE THREAD

**Issue by maikogoudriaan** [rudsonlive/NavigationDrawer-MaterialDesign#78]
I am trying to implement the libary into my app. The only problem is, what I try, the actionBar text color stays white although I would like another color. Does someone has a solution to this problem?

**Comment by rudsonlive** [comment]
You can use this.getToolbar () method or define a color in your style.

this.getToolbar().setTitleTextColor(ContextCompat.getColor(this, R.color.nliveo_blue_colorPrimary));
