### ISSUE TITLE
Items drawables

### ISSUE THREAD

**Issue by amouly** [rudsonlive/NavigationDrawer-MaterialDesign#8]
Why the example it's using an ImageView and a TextView for every item on the Drawer? I mean, could be this replaced with a TextView and a "drawable left"?.

Thanks!.

**Comment by rudsonlive** [comment]
Hello Adrian okay?

To be honest did not cross my mind to use the "drawable left" and would not
know if I got the exact distance that the documentation of Google asks.

But it's a great observation thanks.

Then I'll do a test.

Em Wed Jan 21 2015 at 17:06:31, Adrián Mouly <notifications@github.com>
escreveu:

**Comment by amouly** [comment]
Thanks!.

This could improve the Drawer performance, because you have 2 o 3 views per item now. But using a drawable inserted on the TextView, you can reduce the amount of views included.

You can read more about this here: http://developer.android.com/reference/android/widget/TextView.html#attr_android:drawableLeft

I forked the project and I'm testing this approach right now.

**Comment by rudsonlive** [comment]
Very good.

All help is welcome friend.
