### ISSUE TITLE
How to update user information throught code?

### ISSUE THREAD

**Issue by ingmrko** [rudsonlive/NavigationDrawer-MaterialDesign#81]
I wish to change the name user throught code, it's possible?

**Comment by rudsonlive** [comment]
To change the Header information, simply set the attribute information below.

// User Information
        this.userName.setText("Rudson Lima");
        this.userEmail.setText("rudsonlive@gmail.com");
        this.userPhoto.setImageResource(R.drawable.ic_rudsonlive);
        this.userBackground.setImageResource(R.drawable.ic_user_background_first);
