### ISSUE TITLE
How can I set my own limit for the item counter ?

### ISSUE THREAD

**Issue by StevenWatremez** [rudsonlive/NavigationDrawer-MaterialDesign#84]
The item counter stop when you arrived at 99+. How can I set my own limit ?

**Comment by rudsonlive** [comment]
Hi.

Today you can not customize it.

The library does not limit its value, she simplismentes only reports that
one item has more than 99 meters.

I believe it is something interesting to leave it in the hands of who is
using the library.

Soon I will be providing a new version.

Thank you for the contact.

2015-12-07 13:48 GMT-03:00 StevenWatremez <notifications@github.com>:

> The item counter stop when you arrived at 99+. How can I set my own limit ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/84>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
