### ISSUE TITLE
Change Font of NavigationDrawer List item (TextView)

### ISSUE THREAD

**Issue by azadso** [rudsonlive/NavigationDrawer-MaterialDesign#86]
How to change the Font of NavigationDrawer List items ? There is no option for that, can you please provide me a way for doing that?
Thanks

**Comment by rudsonlive** [comment]
Unfortunately its not possible. The purpose of the library is showing a navigation on the Google standard. Unfortunately today it is not possible to set a font for the items.

Thank you for the contact.
