### ISSUE TITLE
How Can I Add A Material Actionbar Shadow?

### ISSUE THREAD

**Issue by twocucao** [rudsonlive/NavigationDrawer-MaterialDesign#9]
You Project Is Great to Study From.

I have trouble to Add a actionbar shadow(like material design actionbar does).

I Googled ，read some artilcles about it，but its no use,please give me some hints.

Thank you

**Comment by rudsonlive** [comment]
The shadow of the ActionBar is standard Android 5.0 (API level 21). If you
are using the ActonBar default, you do not have to do anything for the
shadow appear longer automatic.

Now if you are using the Toolbar is only use the command setElevation
(float) for the shadow.

Now if you want to buy in this api less than 21, I believe you have to do
this on their own.

http://stackoverflow.com/questions/26575197/no-shadow-by-default-on-toolbar

Em Thu Jan 22 2015 at 03:40:56, twocucao <notifications@github.com>
escreveu:

**Comment by twocucao** [comment]
Thank you for  your help.
