### ISSUE TITLE
Image in ActionBar

### ISSUE THREAD

**Issue by ingmrko** [rudsonlive/NavigationDrawer-MaterialDesign#90]
Well, I want to put a image how the example in the actionbar, right side, some idea?
![ejemplo](https://cloud.githubusercontent.com/assets/7906589/12186963/2e81bc0c-b56d-11e5-8d49-814b54e851a9.jpg)

**Comment by felixdivo** [comment]
Maybe you can add a completely custom "Toolbar"? (Maybe in a CoordinatorLayout)

**Comment by ingmrko** [comment]
Well, i think to try these option, thank u! :)

**Comment by rudsonlive** [comment]
You can try to customize the toolbar using your native [addView()](https://www.google.com.br/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Android+ToolBar+add+View) method and add a custom layout to it. I do not understand but who knows the right.

this.getToolbar().addView();
