### ISSUE TITLE
update navigation item count

### ISSUE THREAD

**Issue by sameera26** [rudsonlive/NavigationDrawer-MaterialDesign#91]
I could successfully integrate navigation drawer in my project. Now I need to update item count dynamically. I couldn't find any guideline for this. Can you please guide me to achieve this?

**Comment by rudsonlive** [comment]
Hi. Below all methods for the item counter of the list.

/*{ Add a new counter }*/
    public void setNewCounterValue(int position, int value){}

    /*{ Increment the counter (current value + new value) }*/
    public void setIncreasingCounterValue(int position, int value){}

    /*{ Decrement the counter (current value - new value) }*/
    public void setDecreaseCountervalue(int position, int value){}

**Comment by sameera26** [comment]
Thanks. Fixed it :+1:
