### ISSUE TITLE
List View Data Source

### ISSUE THREAD

**Issue by ruepay** [rudsonlive/NavigationDrawer-MaterialDesign#92]
Hi i am new to this, so i need help in adding datasource to the list view, something like adding image with name like shown in image attached.
![12](https://cloud.githubusercontent.com/assets/15849525/13173447/8aa830ba-d723-11e5-913b-19e8a7b74fe7.jpg)

**Comment by rudsonlive** [comment]
Hi.

You can use a RelativeLayout and inside it put a ImageView and a TextView.
The TextView you place to stay over the ImageView and sets it to stay like
android: layout_alignParentBottom = "true"

By doing this you will have + - the result you need.

Good luck.

2016-02-19 7:42 GMT-03:00 aravindh <notifications@github.com>:

> Hi i am new to this, so i need help in adding datasource to the list view,
> something like adding image with name like shown in image attached.
> [image: 12]
> <https://cloud.githubusercontent.com/assets/15849525/13173447/8aa830ba-d723-11e5-913b-19e8a7b74fe7.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/92>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
