### ISSUE TITLE
Custom header

### ISSUE THREAD

**Issue by sameera26** [rudsonlive/NavigationDrawer-MaterialDesign#94]
Can I add a custom header instead of default? I tried customHeader(). But it didn't work.

**Comment by rudsonlive** [comment]
Hi. If you are in the demo
<https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/blob/master/demo/src/main/java/br/liveo/ndrawer/ui/activity/MainActivity.java>
project, just uncomment the lines 58, 59, 60 and 83. So already have a
header customized it on the menu.

Thanks you.

2016-02-25 6:16 GMT-03:00 sameera26 <notifications@github.com>:

> Can I add a custom header instead of default? I tried customHeader(). But
> it didn't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rudsonlive/NavigationDrawer-MaterialDesign/issues/94>.
>



-- 
*Rudson Lima ( live-O )* Desenvolvedor Android
*Contato* +55 85 87050560* - *Fortaleza-ce
*Google Play *CepLive-O e Navigation Drawer - Live-O
<https://play.google.com/store/apps/developer?id=Rudson+Lima>
*Social* facebook <https://www.facebook.com/rudsonlive> | google+
<http://google.com/+RudsonLima-O> | linkedin
<http://br.linkedin.com/in/rudsonlive/>
