### ISSUE TITLE
navigation drawer open/close listener

### ISSUE THREAD

**Issue by sameera26** [rudsonlive/NavigationDrawer-MaterialDesign#95]
How can set listener for navigation drawer open/close event? Thanks!

**Comment by rudsonlive** [comment]
Hi.
You can use the following method.

    .setOnPrepareOptionsMenu(onPrepare)
    private OnPrepareOptionsMenuLiveo onPrepare = new OnPrepareOptionsMenuLiveo() {
        @Override
        public void onPrepareOptionsMenu(Menu menu, int position, boolean visible) {
        }
    };

**Comment by sameera26** [comment]
It works. Many Thanks mate :)
